### ISSUE TITLE
Вопросы по тесту 3_8

### ISSUE THREAD

**Issue by 4a1ka** [NemirovichMark/BIVT_2024_Lab_4#5]
https://github.com/NemirovichMark/BIVT_2024_Lab_4/blob/6a7d6b03c4999a8b599a468191bbfc005c1dbd5f/Lab4Tests/ProgramTests.cs#L1577-L1613

Ответ в тесте:
```
{ 9, 10, 11, 15, 15 },
1, 2, -3, 7, 7 },
5, 6, -7, 8, 9},
-13, 14, 25, 25, -19 },
5, 6, -7, 9, -11 },
-13, 14, 25, 25, -19 },
0, 0, -1, -2, -3 }
```
Ответ, что выходит у меня с помощью сортировки : 
```
9 10 11 15 15
 1 2 -3 7 7
5 6 -7 8 9
5 6 -7 9 -11
13 14 25 25 -19
13 14 25 25 -19
0 0 -1 -2 -3
```
По сути оба ответа верные, но отличаются из-за строк, содержащих одинаковое количество положительных элементов.

**Comment by NemirovichMark** [comment]
Здравствуйте, Анастасия. Да, сложный номер. Используйте не перестановку строк, а сдвиг, чтобы сохранить исходную последовательность

**Comment by 4a1ka** [comment]
Но в результате сдвига так же получается матрица, которую я получила в своём ответе.
Для примера:
Исходная матрица:
```
{ 1, 2, -3, 7, 7 }, 
{ 5, 6, -7, 9, -11 }, 
{ 9, 10, 11, 15, 15 }, 
{ -13, 14, 25, 25, -19 }, 
{ 5, 6, -7, 8, 9}, 
{-13, 14, 25, 25, -19 }, 
 {0, 0, -1, -2, -3 } 
```
Начинаем сдвиги:
```
{ 9, 10, 11, 15, 15 }, 
{ 1, 2, -3, 7, 7 }, 
{ 5, 6, -7, 9, -11 }, 
{ -13, 14, 25, 25, -19 }, 
{ 5, 6, -7, 8, 9}, 
{-13, 14, 25, 25, -19 }, 
 {0, 0, -1, -2, -3 } 

{ 9, 10, 11, 15, 15 }, 
{ 1, 2, -3, 7, 7 }, 
{ 5, 6, -7, 8, 9}, 
{ 5, 6, -7, 9, -11 }, 
{ -13, 14, 25, 25, -19 }, 
{-13, 14, 25, 25, -19 }, 
 {0, 0, -1, -2, -3 } 
```
В результате выходит тот же ответ, что и при сортировке пузырьком, который, в результате своей работы, производит сдвиги элемента.

**Comment by NemirovichMark** [comment]
А, в самом тесте неверно строки стоят. Но сделали Вы правильно. Сейчас перепроверю, по идее должен пройти... да, проходит 3_8. Тогда только 1_18 поправить. И файл с тестами обновите, пожалуйста, новый прикрепил.
